### ISSUE TITLE
NoMethodError (undefined method `wait_readable' for #<OpenSSL::SSL::SSLSocket:0x00007fc7641dea60>)

### ISSUE THREAD

**Issue by motymichaely** [contribsys/faktory_worker_ruby#59]
Faktory client fails to connect to Faktory server behind AWS Network Load Blanacer with TLS listener.

Establishing a simple Faktory client connection to a Faktory server behind an [AWS Network Load Balancer with TLS listener](https://aws.amazon.com/blogs/aws/new-tls-termination-for-network-load-balancers/) fails:

```
require 'faktory'
# This is required or otherwise a NameError (uninitialized constant Faktory::Client::OpenSSL) error is raised
require 'openssl' 

client = Faktory::Client.new
```

The stacktrace:
```
Traceback (most recent call last):
        7: from ~/.rbenv/versions/2.7.2/bin/irb:23:in `<main>'
        6: from ~/.rbenv/versions/2.7.2/bin/irb:23:in `load'
        5: from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        4: from (irb):2
        3: from (irb):2:in `new'
        2: from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/faktory_worker_ruby-1.1.0/lib/faktory/client.rb:58:in `initialize'
        1: from ~/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/faktory_worker_ruby-1.1.0/lib/faktory/client.rb:247:in `open'
NameError (uninitialized constant Faktory::Client::OpenSSL)
Did you mean?  OpenStruct
```

NOTE: Establishing the same connection using [Go client](https://github.com/contribsys/faktory/blob/master/client/client.go) works as expected.

---

Gemfile:
```
source 'https://rubygems.org'

ruby '2.7.2'

gem 'faktory_worker_ruby'
gem 'openssl'
```

Gemfile.lock:
```
GEM
  remote: https://rubygems.org/
  specs:
    connection_pool (2.2.5)
    faktory_worker_ruby (1.1.0)
      connection_pool (~> 2.2, >= 2.2.2)
    openssl (2.2.0)

PLATFORMS
  ruby

DEPENDENCIES
  faktory_worker_ruby
  openssl

RUBY VERSION
   ruby 2.7.2p137

BUNDLED WITH
   2.1.4
```

**Comment by cjbottaro** [comment]
Any chance we can get a release cut? Running into this issue with `1.1.0`.

**Comment by mperham** [comment]
Is master working for you?

**Comment by cjbottaro** [comment]
Yup!

**Comment by mperham** [comment]
10-4, expect 1.1 next week.
